### PR TITLE
updated to using svd2rust 0.12.0

### PR DESCRIPTION
**Pull request by wendeldr**
Hey japaric, 
I regenerated the lib.rs file using a newer version of svd2rust (0.12.0) so it can be used with cortex-m-rtfm.

### CODE REVIEW

**Comment by therealprof** [comment]
You might be interested in my new crates https://github.com/therealprof/nrf51 and https://github.com/therealprof/nrf51-hal.

**Comment by japaric** [comment]
@wendeldr I'm not actively working with this chip at the moment so I would suggest using @therealprof's crate instead.

@therealprof if you are interested I can make you a co-owner of the [`nrf51`] crate on crates.io so you can publish a new version.

[`nrf51`]: https://crates.io/crates/nrf51

**Comment by therealprof** [comment]
@japaric I take it. Guess it's time to get acquainted with crates.io for me.

**Comment by wendeldr** [comment]
Thanks guys I'll work with therealprof's repos for now.  Let me know if you end up publishing a new version.

**Comment by japaric** [comment]
@therealprof you don't seem to be registered on crates.io; or at least not with "therealprof" username.

> $ cargo owner --add therealprof
> error: failed to invite owners to crate nrf51: api errors: could not find user with login `therealprof`

Let me know when you register to crates.io and I'll make you an owner of the `nrf51` crate.

**Comment by therealprof** [comment]
@japaric Try now, please.

**Comment by japaric** [comment]
@therealprof done. You should have received an invitation (?).

**Comment by therealprof** [comment]
@japaric It is done. I've updated the crate with an my version. Please let me know if something isn't to your liking.

**Comment by japaric** [comment]
@therealprof LGTM. Thanks for publishing a new version!

**Pull request closed without merging**
