### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit bc41724 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit bc41724 with merge bc41724...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/nrf51/builds/234892938?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing bc417244df6cd68bf98fdd4014a909f578152858 to master...

**Pull request merged**
